// <auto-generated />
namespace OneToOneEntityFrameworkApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class empDepartment1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(empDepartment1));
        
        string IMigrationMetadata.Id
        {
            get { return "202103230717304_empDepartment1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
